config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, only: %i[create show]
  resource :search, only: %i[new show edit]

  root 'welcome#index'

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
    end

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :routes
    resources :tickets
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carriage.rb
class Carriage < ApplicationRecord
  belongs_to :train, optional: true
  validates :number, :top_seats, :bottom_seats, presence: true
  validates :number, uniqueness: { scope: :train_id }, if: :train_id
  validates :number, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  before_validation :set_number, if: :train_id, on: :create

  scope :economy, -> { where(type: 'EconomyCarriage') }
  scope :coupe, -> { where(type: 'CoupeCarriage') }
  scope :ordered, -> { order(:number) }

  private

  def set_number
    self.number = train.carriages.count + 1
  end
end

app/models/coupe_carriage.rb
class CoupeCarriage < Carriage
end

app/models/economy_carriage.rb
class EconomyCarriage < Carriage
  validates :side_top_seats, :side_bottom_seats, presence: true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :trains, foreign_key: :current_station_id
  has_many :railway_stations_route
  has_many :routes, through: :railway_stations_route

  validates :title, presence: true,
                    length: { minimum: 2 }

  scope :ordered, -> { joins(:railway_stations_route).order('railway_stations_routes.position').uniq }

  def update_position(route, position)
    station_route = station_route(route)
    station_route&.update(position: position)
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  protected

  def station_route(route)
    station_route ||= railway_stations_route.where(route: route).first
  end
end

app/models/railway_stations_route.rb
# frozen_string_literal: true

class RailwayStationsRoute < ActiveRecord::Base
  belongs_to :railway_station
  belongs_to :route

  validates :railway_station_id, uniqueness: { scope: :route_id }
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :railway_stations_route
  has_many :railway_stations, through: :railway_stations_route

  validates :name, presence: true
  validate :stations_count

  before_validation :set_name

  private

  def set_name
    self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    errors.add(:base, 'Route should contain at least 2 stations') if railway_stations.size < 2
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', optional: true
  has_many :carriages, dependent: :destroy

  validates :number, presence: true,
                     length: { minimum: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :tickets
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  layout 'admin'

  protected

  def check_admin
    redirect_to root_path, alert: 'You do not have permission to view this page' unless current_user.admin?
  end
end

app/controllers/admin/railway_stations_controller.rb
class Admin::RailwayStationsController < Admin::BaseController
  before_action :set_railway_station, only: %i[show edit update destroy update_position]

  def index
    @railway_stations = RailwayStation.all
  end

  def show; end

  def new
    @railway_station = RailwayStation.new
  end

  def edit; end

  def create
    @railway_station = RailwayStation.new(railway_station_params)
    if @railway_station.save
      redirect_to [:admin, @railway_station]
    else
      render :new
    end
  end

  def update
    if @railway_station.update(railway_station_params)
      redirect_to admin_railway_stations_path
    else
      render :new
    end
  end

  def destroy
    @railway_station.destroy
    redirect_to admin_railway_stations_path
  end

  def update_position
    @route = Route.find(params[:route_id])
    @railway_station.update_position(@route, params[:position])
    redirect_to [:admin, @route]
  end

  private

  def set_railway_station
    @railway_station = RailwayStation.find(params[:id])
  end

  def railway_station_params
    params.require(:railway_station).permit(:title)
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: %i[show edit update destroy]

  def index
    @routes = Route.all
  end

  def show; end

  def new
    @route = Route.new
  end

  def edit; end

  def create
    @route = Route.new(route_params)
    @route.railway_stations << RailwayStation.where(id: params[:route][:railway_stations])
    if @route.save
      redirect_to admin_routes_path
    else
      render :new
    end
  end

  def update
    @route.railway_stations = RailwayStation.where(id: params[:route][:railway_stations])
    if @route.update(route_params)
      redirect_to [:admin, @route]
    else
      render :new
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show; end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, only: :create

  def show
    @ticket = Ticket.find(params[:id])
  end

  def create
    @ticket = current_user.tickets.new
    if @ticket.save
      redirect_to @ticket
    else
      redirect_to search_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
# frozen_string_literal: true

module RailwayStationsHelper
end

app/helpers/routes_helper.rb
# frozen_string_literal: true

module RoutesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/trains_helper.rb
# frozen_string_literal: true

module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/railway_stations/_form.html.erb
<%= form_for [:admin, @railway_station] do |form| %>
  <%= render 'common/errors', resource: @railway_station %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit "#{@railway_station.new_record? ? 'Create' : 'Update'}" %>
  </div>
<% end %>

app/views/admin/railway_stations/_railway_station.html.erb
<tr>
  <td><%= railway_station.title %></td>
  <td><%= link_to 'Show', [:admin, railway_station] %></td>
  <td><%= link_to 'Edit', edit_admin_railway_station_path(railway_station) %></td>
  <td><%= link_to 'Destroy', [:admin, railway_station], method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_railway_stations_path %>

app/views/admin/railway_stations/index.html.erb
<h1>Railway Stations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @railway_stations %>
  </tbody>
</table>

<br>
<%= link_to 'New Railway Station', new_admin_railway_station_path %>
<br>
<%= link_to 'back to main page', root_path %>

app/views/admin/railway_stations/new.html.erb
<h1>New Railway Station</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_railway_stations_path %>

app/views/admin/railway_stations/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<% if @railway_station.routes.empty? %>
  <p>Station has no routes</p>
<% else %>
  <p> Station's routes:
    <ul>
      <% @railway_station.routes.each do |route| %>
        <li><%= route.name %></li>
      <% end %>
    </ul>
  </p>
<% end %>

<p>Trains on the station:</p>
<ul>
  <% @railway_station.trains.each do |train| %>
    <li><%= train.number %></li>
  <% end %>
</ul>
<%= link_to 'Edit', edit_admin_railway_station_path(@railway_station) %> |
<%= link_to 'Back', admin_railway_stations_path %>