config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, only: %i[create show]
  resource :search, only: %i[new show edit]

  root 'welcome#index'

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
    end

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :routes
    resources :tickets
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carriage.rb
class Carriage < ApplicationRecord
  belongs_to :train, optional: true
  validates :number, :top_seats, :bottom_seats, presence: true
  validates :number, uniqueness: { scope: :train_id }, if: :train_id
  validates :number, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  before_validation :set_number, if: :train_id, on: :create

  scope :economy, -> { where(type: 'EconomyCarriage') }
  scope :coupe, -> { where(type: 'CoupeCarriage') }
  scope :ordered, -> { order(:number) }

  private

  def set_number
    self.number = train.carriages.count + 1
  end
end

app/models/coupe_carriage.rb
class CoupeCarriage < Carriage
end

app/models/economy_carriage.rb
class EconomyCarriage < Carriage
  validates :side_top_seats, :side_bottom_seats, presence: true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :trains, foreign_key: :current_station_id
  has_many :railway_stations_route
  has_many :routes, through: :railway_stations_route

  validates :title, presence: true,
                    length: { minimum: 2 }

  scope :ordered, -> { joins(:railway_stations_route).order('railway_stations_routes.position').uniq }

  def update_position(route, position)
    station_route = station_route(route)
    station_route&.update(position: position)
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  protected

  def station_route(route)
    station_route ||= railway_stations_route.where(route: route).first
  end
end

app/models/railway_stations_route.rb
# frozen_string_literal: true

class RailwayStationsRoute < ActiveRecord::Base
  belongs_to :railway_station
  belongs_to :route

  validates :railway_station_id, uniqueness: { scope: :route_id }
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :railway_stations_route
  has_many :railway_stations, through: :railway_stations_route

  validates :name, presence: true
  validate :stations_count

  before_validation :set_name

  private

  def set_name
    self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    errors.add(:base, 'Route should contain at least 2 stations') if railway_stations.size < 2
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', optional: true
  has_many :carriages, dependent: :destroy

  validates :number, presence: true,
                     length: { minimum: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :tickets
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  layout 'admin'

  protected

  def check_admin
    redirect_to root_path, alert: 'You do not have permission to view this page' unless current_user.admin?
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: %i[show edit update destroy]

  def index
    @routes = Route.all
  end

  def show; end

  def new
    @route = Route.new
  end

  def edit; end

  def create
    @route = Route.new(route_params)
    @route.railway_stations << RailwayStation.where(id: params[:route][:railway_stations])
    if @route.save
      redirect_to admin_routes_path
    else
      render :new
    end
  end

  def update
    @route.railway_stations = RailwayStation.where(id: params[:route][:railway_stations])
    if @route.update(route_params)
      redirect_to [:admin, @route]
    else
      render :new
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name)
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: %i[show edit update destroy]

  def index
    @trains = Train.all
  end

  def show; end

  def new
    @train = Train.new
  end

  def edit; end

  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to admin_trains_path
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to admin_trains_path
    else
      render :new
    end
  end

  def destroy
    @train.destroy
    redirect_to admin_trains_path
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show; end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, only: :create

  def show
    @ticket = Ticket.find(params[:id])
  end

  def create
    @ticket = current_user.tickets.new
    if @ticket.save
      redirect_to @ticket
    else
      redirect_to search_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
# frozen_string_literal: true

module RailwayStationsHelper
end

app/helpers/routes_helper.rb
# frozen_string_literal: true

module RoutesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/trains_helper.rb
# frozen_string_literal: true

module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/routes/_form.html.erb
<%= form_for [:admin, @route] do |form| %>
  <%= render 'common/errors', resource: @route %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :railway_stations %>
    <%= form.collection_select :railway_stations, RailwayStation.all, :id, :title, {}, { :multiple => :true } %>
  </div>

  <div class="actions">
    <%= form.submit "#{@route.new_record? ? 'Create' : 'Update'}" %>
  </div>
<% end %>

app/views/admin/routes/_route.html.erb
<tr>
  <td><%= route.name %></td>
  <td><%= link_to 'Show', [:admin, route] %></td>
  <td><%= link_to 'Edit', edit_admin_route_path(route) %></td>
  <td><%= link_to 'Destroy', [:admin, route], method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/routes/edit.html.erb
<h1>Editing Routes</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_routes_path %>

app/views/admin/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @routes %>
  </tbody>
</table>

<br>
<%= link_to 'New Route', new_admin_route_path %><br>
<%= link_to 'back to main page', root_path %>

app/views/admin/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_routes_path %>

app/views/admin/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Route name:</strong>
  <%= @route.name %>
</p>

<p>
  <strong> Stations:</strong>
  <% if @route.railway_stations.empty? %>
    List is empty
  <% else %>
    <table>

      <thead>
        <tr>
          <td width="100px"> Station's name</td>
          <td>Position</td>
        </tr>
      </thead>

      <tbody>
        <% @route.railway_stations.ordered.each do |station| %>
        <tr>
          <td><%= station.title %></td>
          <td>
            <%= form_tag update_position_admin_railway_station_path(station), method: :patch do %>
              <%= number_field_tag :position, station.position_in(@route) %>
              <%= hidden_field_tag :route_id, @route.id %>
              <%= submit_tag "Change" %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>

    </table>
  <% end %>
</p>
<%= link_to 'Edit', edit_admin_route_path(@route) %> |
<%= link_to 'Back', admin_routes_path %>

app/views/admin/trains/_form.html.erb
<%= form_for [:admin, @train] do |form| %>
  <%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :current_station, 'Current station' %>
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="actions">
    <%= form.submit "#{@train.new_record? ? 'Create' : 'Update'}" %>
  </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Show', [:admin, train] %></td>
  <td><%= link_to 'Edit', edit_admin_train_path(train) %></td>
  <td><%= link_to 'Destroy', [:admin, train], method: :delete, data: { confirm: 'are you sure?' } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_trains_path %>

app/views/admin/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>
<%= link_to 'New Train', new_admin_train_path %><br>
<%= link_to 'Back to main page', root_path %>

app/views/admin/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_trains_path %>

app/views/admin/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<p><strong>Current station:</strong>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %>
  <% else %>
     ---
  <% end %>
</p>

<p>
  <strong> Carriages:</strong>
  <ul>
    <% @train.carriages.each do |carriage| %>
      <li><%= link_to "Carriage № #{carriage.number}", [:admin, carriage] %></li>
    <% end %>
  </ul>
</p>

<p>
  <%= link_to 'Add Carriage', new_admin_train_carriage_path(@train) %>
</p>

<%= link_to 'Edit', edit_admin_train_path(@train) %> |
<%= link_to 'Back', admin_trains_path %>

app/views/tickets/show.html.erb
<p> ticket was bought by: <%= @ticket.user.email%>  </p>